spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:///test-database

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.SQL: DEBUG

service.host: http://localhost:8080/