spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/urlshortener
    username: user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.SQL: DEBUG

service.host: http://localhost:8080/